category/urls.py
from django.test import TestCase

# Create your tests here.
from django.urls import path

from category.views import CategoryaddView, CategoryView, DeletecategoryView, UpdatecategoryView

app_name = 'category'

urlpatterns = [
    path('', CategoryView.as_view(), name='list'),
    path('categoryadd/', CategoryaddView.as_view(), name='create'),
    path('updatecategory/<int:pk>/', UpdatecategoryView.as_view(), name='update'),
    path('deletecategory/<int:pk>/', DeletecategoryView.as_view(), name='delete'),

]

djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('category/', include('category.urls', namespace='category')),
    path('books/', include('books.urls', namespace='books')),
    path('', include('home.urls', namespace='home')),
    path('staff/', include('staff.urls', namespace='staff')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.test import TestCase

# Create your tests here.
from django.urls import path

from home.views import HomeTemplateView, BookDetailView

app_name = 'home'

urlpatterns = [
    path('book/<int:pk>/', BookDetailView.as_view(), name='detail'),
    path('category/<int:pk>/', HomeTemplateView.as_view(), name='category'),
    path('', HomeTemplateView.as_view(), name='home'),
]

staff/urls.py
from django.test import TestCase

# Create your tests here.
from django.urls import path

from staff.views import Staffview

app_name = 'staff'
urlpatterns = [
    path('', Staffview.as_view())
]

category/models.py
from django.db import models


class CategoryModel(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        retufrom django.db import models


class CategoryModel(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

home/models.py
from django.db import models




staff/models.py
from django.db import models


class StaffModel(models.Model):
    image = models.ImageField(upload_to='staff')
    name = models.CharField(max_lefrom django.db import models


class StaffModel(models.Model):
    image = models.ImageField(upload_to='staff')
    name = models.CharField(max_length=50)
    position = models.CharField(max_length=50)
    info = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'staff'
        verbose_name_plural = 'staff'

category/forms.py
from django import forms

from category.models import CategoryModel


class CategoryModelfofrom django import forms

from category.models import CategoryModel


class CategoryModelforms(forms.ModelForm):
    class Meta:
        model = CategoryModel
        fields = ['title']

category/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import UpdateView, DeleteView, ListView, CreateView

from category.forms import CategoryModelforms
from category.models import CategoryModel


class CategoryView(LoginRequiredMixin, ListView):
    template_name = 'category.html'
    model = CategoryModel

    def get_context_data(self, **kwargs):
        context = super().get_context_datfrom django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import UpdateView, DeleteView, ListView, CreateView

from category.forms import CategoryModelforms
from category.models import CategoryModel


class CategoryView(LoginRequiredMixin, ListView):
    template_name = 'category.html'
    model = CategoryModel

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Category'
        return context


class CategoryaddView(LoginRequiredMixin, CreateView):
    template_name = 'form.html'
    form_class = CategoryModelforms

    def get_success_url(self):
        return reverse('category:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Categoryadd'
        return context


class UpdatecategoryView(LoginRequiredMixin, UpdateView):
    model = CategoryModel
    form_class = CategoryModelforms
    template_name = 'form.html'

    def get_success_url(self):
        return reverse('category:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update Category'
        return context


class DeletecategoryView(LoginRequiredMixin, DeleteView):
    model = CategoryModel

    def get_success_url(self):
        return reverse('category:list')

home/views.py
from math import ceil

from django.views.generic import ListView, DetailView

from books.models import BookModel


class HomeTemplateView(ListView):
    template_name = 'home.html'
    model = BookModel
    paginate_by = 3

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        if pk:
            returfrom math import ceil

from django.views.generic import ListView, DetailView

from books.models import BookModel


class HomeTemplateView(ListView):
    template_name = 'home.html'
    model = BookModel
    paginate_by = 3

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        if pk:
            return BookModel.objects.filter(category_id=pk).order_by('-pk')
        else:
            return BookModel.objects.order_by('-pk')

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     x = ceil(BookModel.objects.count() / self.paginate_by)
    #
    #     context['range'] = range(x)
    #     return context


class BookDetailView(DetailView):
    template_name = 'book_detail.html'
    model = BookModel

staff/views.py
from django.db.models import Q
from django.views.generic import ListView

from staff.models import StaffModel


class Staffview(ListViewfrom django.db.models import Q
from django.views.generic import ListView

from staff.models import StaffModel


class Staffview(ListView):
    template_name = 'staff.html'
    model = StaffModel

    def get_queryset(self):
        q = self.request.GET.get('q', '')
        return StaffModel.objects.filter(Q(name__icontains=q) |
                                         Q(position__icontains=q)
                                         )

templates/base_home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Album example · Bootstrap v4.6</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">Books</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% for i in category %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:category' pk=i.pk %}">{{ i.title }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</nav>
{% block content %}

{% endblock %}


<script src="https://code.jquery.com/jquery-3.5.1.s{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Album example · Bootstrap v4.6</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">Books</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% for i in category %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:category' pk=i.pk %}">{{ i.title }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</nav>
{% block content %}

{% endblock %}


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/books_list.html
{% extends 'basa.html' %}
{% load cropping %}
{% block content %}
    <div class="container mt-2">
        <table class="table table-hover">
            <head>
                <tr>
                    <th>Title</th>
                    <th>Image</th>
                    <th>Description</th>
                    <th>Author</th>
                    <th>category</th>
                    <th>page</th>
                    <th>Created_at</th>
                    <th>update_at</th>
                    <th>update</th>
                </tr>
            </head>
            <tbody>
            {% for book in object_list %}
                <tr>
                    <td>{{ book.title|default:'-' }}</td>
                    <td><img src="{% cropped_thumbnail book "cropping" scale=0.5 %}"></td>
                    <td>{{ book.description|safe }}</td>
                    <td>{{ book.author.name|default:'-' }}</td>
                    <td>{{ book.category.title|default:'-' }}</td>
                    <td>{{ book.page_count|default:'-' }}</td>
                    <td>{{ book.created_at|date:'d-m-Y H:i' }}</td>
                    <td>{{ book.update_at|date:'d-m-Y H:i' }}</td>
                    <td>
                       <div class="row">
                        <div class="col-6">
          {% extends 'basa.html' %}
{% load cropping %}
{% block content %}
    <div class="container mt-2">
        <table class="table table-hover">
            <head>
                <tr>
                    <th>Title</th>
                    <th>Image</th>
                    <th>Description</th>
                    <th>Author</th>
                    <th>category</th>
                    <th>page</th>
                    <th>Created_at</th>
                    <th>update_at</th>
                    <th>update</th>
                </tr>
            </head>
            <tbody>
            {% for book in object_list %}
                <tr>
                    <td>{{ book.title|default:'-' }}</td>
                    <td><img src="{% cropped_thumbnail book "cropping" scale=0.5 %}"></td>
                    <td>{{ book.description|safe }}</td>
                    <td>{{ book.author.name|default:'-' }}</td>
                    <td>{{ book.category.title|default:'-' }}</td>
                    <td>{{ book.page_count|default:'-' }}</td>
                    <td>{{ book.created_at|date:'d-m-Y H:i' }}</td>
                    <td>{{ book.update_at|date:'d-m-Y H:i' }}</td>
                    <td>
                       <div class="row">
                        <div class="col-6">
                            <a href="{% url 'books:update' pk=book.pk %}">
                                <i class="fa fa-pen text-warning"></i>
                            </a>
                        </div>
                        <div class="col-6 px-0">
                            <form onsubmit="return confirm('You sure?')" method="POST" action="{% url 'books:delete' pk=book.pk %}">
                                {% csrf_token %}
                                <button class="submit-icon" type="submit">
                                    <i class="fa fa-trash text-danger"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/category.html
{% extends 'basa.html' %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    <div class="container mt-2">
        <table class="table table-bordered">
        <thead>
        <tr>
            <th>Title</th>
            <th width="150px">Action</th>{% extends 'basa.html' %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    <div class="container mt-2">
        <table class="table table-bordered">
        <thead>
        <tr>
            <th>Title</th>
            <th width="150px">Action</th>
        </tr>
        </thead>
        <tbody>
        {% for i in object_list %}
            <tr>
                <td>{{ i.title }}</td>
                <td class="text-center">
                    <div class="row">
                        <div class="col-6">
                            <a href="{% url 'category:update' pk=i.pk %}">
                                <i class="fa fa-pen text-warning"></i>
                            </a>
                        </div>
                        <div class="col-6 px-0">
                            <form onsubmit="return confirm('You sure?')" method="POST" action="/category/delete/{{ i.pk }}/">
                                {% csrf_token %}
                                <button class="submit-icon" type="submit">
                                    <i class="fa fa-trash text-danger"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

templates/home.html
{% extends 'base_home.html' %}
{% load my_filters %}
{% block content %}
    <main role="main">

        <div class="album py-5 bg-light">
            <div class="container">

                <div class="row">
                    {% for data in object_list %}
                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm">
                                <img style='width:100%;' src="{{ data.cover.url }}">
                                <div class="card-body">
                                    <h4 class="card-text">{{ data.title|upper }}</h4>
                                    <p class="card-text">{{ data.title }}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="{% url 'home:detail' pk=data.pk %}">
                                                <button type="button" class="btn btn-sm btn-outline-secondary">View
      {% extends 'base_home.html' %}
{% load my_filters %}
{% block content %}
    <main role="main">

        <div class="album py-5 bg-light">
            <div class="container">

                <div class="row">
                    {% for data in object_list %}
                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm">
                                <img style='width:100%;' src="{{ data.cover.url }}">
                                <div class="card-body">
                                    <h4 class="card-text">{{ data.title|upper }}</h4>
                                    <p class="card-text">{{ data.title }}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="{% url 'home:detail' pk=data.pk %}">
                                                <button type="button" class="btn btn-sm btn-outline-secondary">View
                                                </button>
                                            </a>
                                            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                        </div>
                                        <small class="text-muted">{{ data.created_at|timesince }} oldin</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                <nav class="float-right">
                    <ul class="pagination">

                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                    <span>&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                        {% endif %}
                        {% my_range page_obj.paginator.num_pages as x %}
                        {% for foo in x %}
                            <li class="page-item {% if page_obj.number == forloop.counter %} active {% endif %}">
                                <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                            </li>
                        {% endfor %}



                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                    <span>&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
                </nav>
            </div>
        </div>
    </main>
{% endblock %}

templates/staff_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" name="q">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </d{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" name="q">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
</nav>
{% block content %}

{% endblock %}
</body>
</html>